version: '2'
services:
  prepapp-app:
    image: prepapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://prepapp-mariadb:3306/prepapp
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  prepapp-mariadb:
    extends:
      file: mariadb.yml
      service: prepapp-mariadb
